# Purpose: Automatically update GitHub curated topics list daily
# Context: Keeps the application's topic list fresh and up-to-date

name: Update Topics

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '0 0 * * *'
  # Allow manual trigger
  workflow_dispatch:

jobs:
  update-topics:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Update stars
        run: bun run update-stars

      - name: Update topics
        run: bun run update-topics

      - name: Update featured repos
        run: bun run feature-repos

      - name: Check for changes
        id: check_changes
        run: |
          git diff --quiet src/lib/all_topics.ts || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Commit and push if changed
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add src/lib/all_topics.ts
          git commit -m "chore: update curated topics list [skip ci]"
          git push